version: '2'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3307:3306
